version: "3"
silent: true

tasks:
  1:
    cmds:
      - |
        mkdir -p ./workshop-devdays-2025/apps/base/podinfo

        cp ./source-files/apps/base/podinfo/kustomization.yaml ./workshop-devdays-2025/apps/base/podinfo/kustomization.yaml
        cp ./source-files/apps/base/podinfo/namespace.yaml ./workshop-devdays-2025/apps/base/podinfo/namespace.yaml

        git -C ./workshop-devdays-2025 add .
        git -C ./workshop-devdays-2025 commit -m "feat: add base podinfo application"
        git -C ./workshop-devdays-2025 push origin main

  2:
    cmds:
      - |
        mkdir -p ./workshop-devdays-2025/apps/development
        mkdir -p ./workshop-devdays-2025/apps/production

        cp ./source-files/apps/development/kustomization.yaml ./workshop-devdays-2025/apps/development/kustomization.yaml
        cp ./source-files/apps/production/kustomization.yaml ./workshop-devdays-2025/apps/production/kustomization.yaml

        git -C ./workshop-devdays-2025 add .
        git -C ./workshop-devdays-2025 commit -m "feat: add development and production overlay"
        git -C ./workshop-devdays-2025 push origin main

  3:
    cmds:
      - |
        cp ./source-files/clusters/local/apps-development.yaml ./workshop-devdays-2025/clusters/local/apps-development.yaml
        cp ./source-files/clusters/local/apps-production.yaml ./workshop-devdays-2025/clusters/local/apps-production.yaml

        git -C ./workshop-devdays-2025 add .
        git -C ./workshop-devdays-2025 commit -m "feat: add development and production overlay"
        git -C ./workshop-devdays-2025 push origin main

  4:
    cmds:
      - |
        cp ./source-files/apps/development/kustomization-patched.yaml ./workshop-devdays-2025/apps/development/kustomization.yaml

        git -C ./workshop-devdays-2025 add .
        git -C ./workshop-devdays-2025 commit -m "fix: reduce replicas to 1 in development overlay"
        git -C ./workshop-devdays-2025 push origin main

  5:
    cmds:
      - |
        mkdir -p ./workshop-devdays-2025/infrastructure
        mkdir -p ./workshop-devdays-2025/repositories

        cp ./source-files/repositories/bitnami.yaml ./workshop-devdays-2025/repositories/bitnami.yaml
        cp ./source-files/infrastructure/sealed-secrets.yaml ./workshop-devdays-2025/infrastructure/sealed-secrets.yaml

        cp ./source-files/clusters/local/repositories.yaml ./workshop-devdays-2025/clusters/local/repositories.yaml
        cp ./source-files/clusters/local/infrastructure.yaml ./workshop-devdays-2025/clusters/local/infrastructure.yaml

        git -C ./workshop-devdays-2025 add .
        git -C ./workshop-devdays-2025 commit -m "feat: deploy sealed-secrets"
        git -C ./workshop-devdays-2025 push origin main

  cleanup:
    cmds:
      - |
        git -C ./workshop-devdays-2025 reset 8579fb3
        git -C ./workshop-devdays-2025 push origin main --force
        git -C ./workshop-devdays-2025 clean -fd

  presentation:
    desc: Export presentations in HTML, PDF and PPTX formats
    cmds:
      - task: presentation-html
      - task: presentation-pdf
      - task: presentation-pptx

  presentation-html:
    desc: Export presentation to HTML
    cmds:
      - echo "📊 Exporting presentation..."
      - marp automating-kubernetes-with-flux.md -o automating-kubernetes-with-flux.html --author "Edwin Bruurs" --title "Automating Kubernetes with Flux"
      - echo "✅ Presentation exported to automating-kubernetes-with-flux.html"

  presentation-pdf:
    desc: Export presentation to PDF
    cmds:
      - echo "📊 Exporting presentation to PDF..."
      - marp automating-kubernetes-with-flux.md -o automating-kubernetes-with-flux.pdf --pdf --allow-local-files --author "Edwin Bruurs" --title "Automating Kubernetes with Flux"
      - echo "✅ Presentation exported to automating-kubernetes-with-flux.pdf"

  presentation-pptx:
    desc: Export presentation to Powerpoint
    cmds:
      - echo "📊 Exporting presentation to Powerpoint..."
      - marp automating-kubernetes-with-flux.md -o automating-kubernetes-with-flux.pptx --pptx --allow-local-files --author "Edwin Bruurs" --title "Automating Kubernetes with Flux"
      - echo "✅ Presentation exported to automating-kubernetes-with-flux.pptx"
